version: '3.8'

services:
  centos-node1:
    image: quay.io/centos/centos:stream9
    container_name: centos-node1
    hostname: centos-node1
    privileged: true
    depends_on:
      centos-node2:
        condition: service_healthy
    networks:
      cluster-net:
        ipv4_address: 172.28.0.11
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - node1-data:/var/lib/pacemaker
    tmpfs:
      - /run
      - /tmp
    entrypoint: ["/bin/bash", "-c"]
    command: 
      - |
        if [ ! -f /usr/sbin/init ]; then
          dnf install -y systemd
        fi
        if [ ! -f /usr/bin/pcs ]; then
          dnf config-manager --set-enabled highavailability
          dnf install -y passwd iputils iproute procps-ng util-linux net-tools
          dnf install -y pacemaker corosync pcs fence-agents-all
          echo ${hapwd} | passwd --stdin hacluster
        fi
        exec /usr/sbin/init
        systemctl start pcsd
    restart: unless-stopped

  centos-node2:
    image: quay.io/centos/centos:stream9
    container_name: centos-node2
    hostname: centos-node2
    privileged: true
    networks:
      cluster-net:
        ipv4_address: 172.28.0.12
    healthcheck:
      test: ["CMD-SHELL", "systemctl is-active pcsd || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - node2-data:/var/lib/pacemaker
    tmpfs:
      - /run
      - /tmp
    entrypoint: ["/bin/bash", "-c"]
    command: 
      - |
        if [ ! -f /usr/sbin/init ]; then
          dnf install -y systemd
        fi
        if [ ! -f /usr/bin/pcs ]; then
          dnf config-manager --set-enabled highavailability
          dnf install -y passwd iputils iproute procps-ng util-linux net-tools
          dnf install -y pacemaker corosync pcs fence-agents-all
          echo ${hapwd} | passwd --stdin hacluster
        fi
        exec /usr/sbin/init
        systemctl start pcsd
    restart: unless-stopped

networks:
  cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  node1-data:
  node2-data:
